### PR TITLE
 cleanDockerImages: byDownloadDate cleanup mode

### PR DESCRIPTION
**Pull request by weakcamel**
Implements byDownloadDate mode of operation - see #333

### CODE REVIEW

**Comment by weakcamel** [comment]
## Tests for maxDays option

### Tests data (input)

```
docker-test/test/v1/manifest.json creat=2022-01-17T10:08:28.118Z modified=2022-01-17T10:10:17.194Z maxDays=1
docker-test/test/v2/manifest.json creat=2022-01-17T10:12:18.444Z modified=2022-01-17T10:12:18.439Z maxDays=1
docker-test/test/v3/manifest.json creat=2022-01-17T10:14:19.751Z modified=2022-01-17T10:14:19.747Z maxDays=1
docker-test/test/v4/manifest.json creat=2022-01-17T10:16:21.080Z modified=2022-01-17T10:16:21.075Z maxDays=1
docker-test/test/v5/manifest.json creat=2022-01-17T10:18:22.315Z modified=2022-01-17T10:18:22.311Z maxDays=1
docker-test/test/v6/manifest.json creat=2022-01-17T10:20:23.568Z modified=2022-01-17T10:20:23.564Z maxDays=1
docker-test/test/v7/manifest.json creat=2022-01-17T10:22:24.817Z modified=2022-01-17T10:22:24.813Z maxDays=1
docker-test/test/v8/manifest.json creat=2022-01-17T10:24:26.491Z modified=2022-01-17T10:24:26.486Z maxDays=1
docker-test/test/v9/manifest.json creat=2022-01-17T10:28:01.737Z modified=2022-01-17T10:28:01.731Z maxDays=1
```

Out of these images, none have been downloaded except for:
* `docker-test/test/v5/manifest.json` downloaded `20-01-22 16:41:48 +00:00`
* `docker-test/test/v8/manifest.json` downloaded `20-01-22 16:44:03 +00:00`


### Test output:

```
+ /usr/bin/curl -sSfL -X POST -u admin:<REDACTED> 'http://localhost:8081/artifactory/api/plugins/execute/cleanDockerImages?params=dryRun=true'
+ jq .
{
  "status": "okay",
  "dryRun": true,
  "deleted": [
    "docker-test:test/v1",
    "docker-test:test/v2",
    "docker-test:test/v3",
    "docker-test:test/v4",
    "docker-test:test/v5",
    "docker-test:test/v6",
    "docker-test:test/v7",
    "docker-test:test/v8",
    "docker-test:test/v9"
  ]
}
```

```
Trigger the plugin - byDownloadDate mode
+ /usr/bin/curl -sSfL -X POST -u admin:<REDACTED> 'http://localhost:8081/artifactory/api/plugins/execute/cleanDockerImages?params=dryRun=true;byDownloadDate=true'
+ jq .
{
  "status": "okay",
  "dryRun": true,
  "deleted": [
    "docker-test:test/v1",
    "docker-test:test/v2",
    "docker-test:test/v3",
    "docker-test:test/v4",
    "docker-test:test/v6",
    "docker-test:test/v7",
    "docker-test:test/v9"
  ]
}
```

## Tests for maxCount option


### Test script

```bash
#!/bin/bash
set -eEuo pipefail

for i in $(seq 1 9 | tac); do
  echo "- - - - - - - - - - - - - - - - - - - - - - - - - - -"
  echo "Changing maxCount to ${i}"
  ./jfrog rt set-props docker-test/test/**/manifest.json "docker.label.com.jfrog.artifactory.retention.maxCount=${i}" >/dev/null 2>&1
  #echo "Trigger the plugin - default mode"
  #./jfrog rt curl -sSfL -X POST "api/plugins/execute/cleanDockerImages?params=dryRun=true" | jq -r ".deleted | .[]"
  echo "Trigger the plugin - byDownloadDate mode"
  ./jfrog rt curl -sSfL -X POST "api/plugins/execute/cleanDockerImages?params=dryRun=true;byDownloadDate=true" | jq -r ".deleted | .[]"
done
```

### Input data

Image versions v1 - v9 were created in order (v1 oldest to v9 latest)

```
docker-test/test/v1/manifest.json creat=2022-01-17T10:08:28.118Z modified=2022-01-17T10:10:17.194Z maxDays=10
docker-test/test/v2/manifest.json creat=2022-01-17T10:12:18.444Z modified=2022-01-17T10:12:18.439Z maxDays=10
docker-test/test/v3/manifest.json creat=2022-01-17T10:14:19.751Z modified=2022-01-17T10:14:19.747Z maxDays=10
docker-test/test/v4/manifest.json creat=2022-01-17T10:16:21.080Z modified=2022-01-17T10:16:21.075Z maxDays=10
docker-test/test/v5/manifest.json creat=2022-01-17T10:18:22.315Z modified=2022-01-17T10:18:22.311Z maxDays=10
docker-test/test/v6/manifest.json creat=2022-01-17T10:20:23.568Z modified=2022-01-17T10:20:23.564Z maxDays=10
docker-test/test/v7/manifest.json creat=2022-01-17T10:22:24.817Z modified=2022-01-17T10:22:24.813Z maxDays=10
docker-test/test/v8/manifest.json creat=2022-01-17T10:24:26.491Z modified=2022-01-17T10:24:26.486Z maxDays=10
docker-test/test/v9/manifest.json creat=2022-01-17T10:28:01.737Z modified=2022-01-17T10:28:01.731Z maxDays=10
```


Out of these images, only these 2 have been downloaded:
* `docker-test/test/v5/manifest.json` downloaded `20-01-22 16:41:48 +00:00` (earlier)
* `docker-test/test/v8/manifest.json` downloaded `20-01-22 16:44:03 +00:00` (later)

### Test output for  `byDownloadDate`

```
root@artifactory:~# ./trigger_clean.sh
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 9
Trigger the plugin - byDownloadDate mode
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 8
Trigger the plugin - byDownloadDate mode
docker-test:test/v1
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 7
Trigger the plugin - byDownloadDate mode
docker-test:test/v1
docker-test:test/v2
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 6
Trigger the plugin - byDownloadDate mode
docker-test:test/v1
docker-test:test/v2
docker-test:test/v3
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 5
Trigger the plugin - byDownloadDate mode
docker-test:test/v1
docker-test:test/v2
docker-test:test/v3
docker-test:test/v4
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 4
Trigger the plugin - byDownloadDate mode
docker-test:test/v1
docker-test:test/v2
docker-test:test/v3
docker-test:test/v4
docker-test:test/v6
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 3
Trigger the plugin - byDownloadDate mode
docker-test:test/v1
docker-test:test/v2
docker-test:test/v3
docker-test:test/v4
docker-test:test/v6
docker-test:test/v7
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 2
Trigger the plugin - byDownloadDate mode
docker-test:test/v1
docker-test:test/v2
docker-test:test/v3
docker-test:test/v4
docker-test:test/v6
docker-test:test/v7
docker-test:test/v9
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 1
Trigger the plugin - byDownloadDate mode
docker-test:test/v1
docker-test:test/v2
docker-test:test/v3
docker-test:test/v4
docker-test:test/v6
docker-test:test/v7
docker-test:test/v9
docker-test:test/v5
root@artifactory:~#
```

Note the 2 last cases: image `v5` was identified for removal as last and the last downloaded image `v8` was not marked for removal at all.

### For reference - test output for the default mode (by creation date - existing plugin behaviour).

```
oot@artifactory:~# ./trigger_clean.sh
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 9
Trigger the plugin - default mode
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 8
Trigger the plugin - default mode
docker-test:test/v1
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 7
Trigger the plugin - default mode
docker-test:test/v1
docker-test:test/v2
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 6
Trigger the plugin - default mode
docker-test:test/v1
docker-test:test/v2
docker-test:test/v3
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 5
Trigger the plugin - default mode
docker-test:test/v1
docker-test:test/v2
docker-test:test/v3
docker-test:test/v4
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 4
Trigger the plugin - default mode
docker-test:test/v1
docker-test:test/v2
docker-test:test/v3
docker-test:test/v4
docker-test:test/v5
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 3
Trigger the plugin - default mode
docker-test:test/v1
docker-test:test/v2
docker-test:test/v3
docker-test:test/v4
docker-test:test/v5
docker-test:test/v6
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 2
Trigger the plugin - default mode
docker-test:test/v1
docker-test:test/v2
docker-test:test/v3
docker-test:test/v4
docker-test:test/v5
docker-test:test/v6
docker-test:test/v7
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Changing maxCount to 1
Trigger the plugin - default mode
docker-test:test/v1
docker-test:test/v2
docker-test:test/v3
docker-test:test/v4
docker-test:test/v5
docker-test:test/v6
docker-test:test/v7
docker-test:test/v8
root@artifactory:~#
```

**Comment by weakcamel** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by weakcamel** [comment]
recheck

**Comment by weakcamel** [comment]
recheck

**Comment by weakcamel** [comment]
recheck

**Comment by weakcamel** [comment]
I'm not really sure who's normally reviewing contributions to plugins so trying my luck and looping people who have recently merged their changes in here.

@alexhung @lotooo @yahavi @shrajfr12 would any of you be able to advise what it takes to get this pull request reviewed/merged?

**Comment by lotooo** [comment]
> I'm not really sure who's normally reviewing contributions to plugins so trying my luck and looping people who have recently merged their changes in here.
> 
> @alexhung @lotooo @yahavi @shrajfr12 would any of you be able to advise what it takes to get this pull request reviewed/merged?

I am not part of the `jfrog` org, I can't help :(

**Comment by weakcamel** [comment]
@lotooo no worries and thank you :) I was just trying my luck.

BTW good point about the actual [jfrog organization members](https://github.com/orgs/jfrog/people).

@jbaruch @noamshemesh @freddy33 @elioengcomp @yahavi could any of you perhaps help guide me what can I to have this MR accepted?
Thanks in advance

**Review by alexhung — APPROVED** [review]
Looks ok to me

**Review by shrajfr12 — APPROVED** [review]
LGTM

**Pull request merged**
