### PR TITLE
webhook: Create a formatter for keel.sh

### PR DESCRIPTION
**Pull request by lotooo**
This PR creates a dedicated [keel](https://keel.sh) formatter for the webhook plugin.

### CODE REVIEW

**Comment by lotooo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lotooo** [comment]
recheckcla

**Comment by jfrog-aparicio** [comment]
Looks okay to me, as in it should work as-is. 

There are potential improvement areas in the way the docker registry is passed. For example, you could consider making the DockerRegistryUrl optional and if it is not passed, simply assume the [path format](https://www.jfrog.com/confluence/display/JFROG/Getting+Started+with+Artifactory+as+a+Docker+Registry#GettingStartedwithArtifactoryasaDockerRegistry-WithoutaReverseProxy), which is baseUrl/repo/image-name:path (which is what Spinnaker does)

**Comment by lotooo** [comment]
> There are potential improvement areas in the way the docker registry is passed. For example, you could consider making the DockerRegistryUrl optional and if it is not passed, simply assume the path format, which is baseUrl/repo/image-name:path (which is what Spinnaker does)

Good idea ! I pushed a change to do it.

**Pull request merged**
