### PR TITLE
inactiveServerCleaner: add correct type and cleanup

### PR DESCRIPTION
**Pull request by dillon-giacoppo**
The type was incorrectly put as List<String> instead of List<ArtifactoryServer>. As groovy is not type-safe this works at runtime but fails compilation within an IDE. Also optimises the artifactoryInactiveServerCleaner to be instantiated once and not on each execution. Also added missing imports and removed unnecessary public modifier.

Overall, just general linting changes.

### CODE REVIEW

**Comment by elioengcomp** [comment]
Hi @dillon-giacoppo,

Thank you for your contribution. It looks good. I'm going to create an internal task to run it against our automated tests and merge it if it pass them.

**Comment by dillon-giacoppo** [comment]
Hi @elioengcomp any update on this?

**Comment by elioengcomp** [comment]
Hi @dillon-giacoppo. Not yet. I'll check and keep you informed.

**Comment by ankushchadha** [comment]
Thanks, @dillon-giacoppo for submitting the PR. We prioritized this for the current leap (sprint).

**Comment by DarthFennec** [comment]
Looks good to me, thanks!

**Pull request merged**
